### ISSUE TITLE
Changing location on in view loaded in the background always will end up at the start

### ISSUE THREAD

**Issue by ehapmgs** [readium/r2-navigator-swift#96] opened 2019-12-31 16:57 UTC
If you try to go the a location on view loaded in the background it will always end up at the start of the resource.

here I am trying to go to the last locater on the resource

![location](https://user-images.githubusercontent.com/26691494/71627948-33dc8900-2bfe-11ea-852b-93e3a9083167.gif)

The reason behind this that  `loadView(at index: Int, location: Locator) ` method will ignore the case were the view is loaded and won't create a new view with initialLocation of the parameter sent to it

check #95 as a suggested solution

**Comment by ehapmgs** [comment] 2020-01-01 14:16
Alternative fix that will prevent calling go method while swiping #97

**Comment by mickael-menu** [comment] 2020-04-16 10:36
@ehapmgs Thanks for your issue report, and sorry for leaving you hanging there!
This seems to have been fixed by [this PR](https://github.com/readium/r2-navigator-swift/pull/104), since I can't reproduce the problem in `develop`. Can you confirm that it's fixed from your side with `develop` branches?

**Comment by mickael-menu** [comment] 2021-02-08 14:48
Please reopen the issue if it's still occurring from `develop`.

**Closed by mickael-menu** 2021-02-08 14:48 UTC
Labels: bug
